# Render Configuration

render:
  services:
    - type: web
      name: ally-scheduler-dashboard
      env: node
      plan: free
      gitSync:
        branch: main
        repo: https://github.com/ahaley08/ally-scheduler-dashboard.git
      buildCommand: 'npm install && npm run build'
      startCommand: 'npm run start'
      envVars:
        - key: NODE_ENV
          value: production
